version: 1.2
workflows:
  - name: TBfastProfiler
    subclass: WDL
    primaryDescriptorPath: /TBfastProfiler.wdl
    testParameterFiles:
      - /local.json
    authors:
      - orcid: 0000-0003-4896-1858